export const CITYNAME = 'USER_CURRENT_CITY_NAME'
export const HISTORYIPT = 'USER_CURRENT_HISTORY_IPT'
export const HISTORYKEY = 'USER_CURRENT_HISTORY_KEY'
export const USERNAME = 'USER_CURRENT_USER_NAME'