
module.exports = {
	lists: [{
		list: [{
			icon: 'https://gw.alicdn.com/tfs/TB19O2WnFGWBuNjy0FbXXb4sXXa-150-150.png',
			name: '美食'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1XO6WnFGWBuNjy0FbXXb4sXXa-150-150.png',
			name: '猫眼电影'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1cGICnNSYBuNjSspjXXX73VXa-150-150.png',
			name: '酒店'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1jhPVnL9TBuNjy0FcXXbeiFXa-150-150.png',
			name: '休闲娱乐'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1eaICnNSYBuNjSspjXXX73VXa-150-150.png',
			name: '外卖'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1ibdyn9tYBeNjSspkXXbU8VXa-150-150.png',
			name: '火锅'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1aWgFnQCWBuNjy0FaXXXUlXXa-150-150.png',
			name: '丽人'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1ki6WnFGWBuNjy0FbXXb4sXXa-150-150.png',
			name: '购物'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1srdyn9tYBeNjSspkXXbU8VXa-150-150.png',
			name: '周边游'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1cGgFnQCWBuNjy0FaXXXUlXXa-150-150.png',
			name: 'KTV'
		}]
	},{
		list: [{
			icon: 'https://gw.alicdn.com/tfs/TB1zXJEn9BYBeNjy0FeXXbnmFXa-150-150.png',
			name: '婚纱摄影'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1zpJEn9BYBeNjy0FeXXbnmFXa-150-150.png',
			name: '生活服务'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1CugpnKOSBuNjy0FdXXbDnVXa-150-150.png',
			name: '景点'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1AXJEn9BYBeNjy0FeXXbnmFXa-150-150.png',
			name: '爱车'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1xegpnKOSBuNjy0FdXXbDnVXa-150-150.png',
			name: '运动健身'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1yKgpnKOSBuNjy0FdXXbDnVXa-150-150.png',
			name: '亲子'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1GegpnKOSBuNjy0FdXXbDnVXa-150-150.png',
			name: '家装'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1i8vYnL9TBuNjy0FcXXbeiFXa-150-150.png',
			name: '学习培训'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1JVJEn9BYBeNjy0FeXXbnmFXa-150-150.png',
			name: '医疗健康'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1HegpnKOSBuNjy0FdXXbDnVXa-150-150.png',
			name: '到家'
		}]
	},{
		list: [{
			icon: 'https://gw.alicdn.com/tfs/TB1p01Gn_tYBeNjy1XdXXXXyVXa-150-150.png',
			name: '小吃快餐'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1ot1Gn_tYBeNjy1XdXXXXyVXa-150-150.png',
			name: '自助餐'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1IlwEnKuSBuNjy1XcXXcYjFXa-150-150.png',
			name: '日本料理'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1pJ1Gn_tYBeNjy1XdXXXXyVXa-150-150.png',
			name: '美发'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1HRwEnKuSBuNjy1XcXXcYjFXa-150-150.png',
			name: '美甲美睫'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1JRjxnMmTBuNjy1XbXXaMrVXa-150-150.png',
			name: '美容SPA'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1S8wEnKuSBuNjy1XcXXcYjFXa-150-150.png',
			name: '瘦身纤体'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1UlwEnKuSBuNjy1XcXXcYjFXa-150-150.png',
			name: '亲子摄影'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1At1Gn_tYBeNjy1XdXXXXyVXa-150-150.png',
			name: '亲子游乐'
		}, {
			icon: 'https://gw.alicdn.com/tfs/TB1PljxnMmTBuNjy1XbXXaMrVXa-150-150.png',
			name: '全部分类'
		}]
	}]
}